title: 胆小鬼大赢家 Julia
description: Just push, win and earn.
show_downloads: false


#baseurl: "/"
url: "https://julia4pr.github.io"


#google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

#theme: # leave it empty

# social
author: Julia
#image: /thumbnail-jumbo.png
twitter:
  username: julia4pr
github:
  owner_name: julia4pr


permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about']
